---
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: web
spec:
  containers:
    - name: front-end-helloworld
      image: rolindroy/helloworld
      ports:
        - containerPort: 80
