---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: env-secret-reader
spec:
  selector:
    matchLabels:
      app: env-secret-reader
  replicas: 1
  template:
    metadata:
      labels:
        app: env-secret-reader
    spec:
      containers:
      - name: env-secret-reader
        image: rolindroy/env-reader:secret-v2
        command: ["python"]
        args: ["./secret-reader.py", "username"]
        env:
        - name: apikey
          valueFrom:
            secretKeyRef:
              name: secret-api
              key: apikey

        - name: username
          valueFrom:
            secretKeyRef:
              name: secret-api
              key: username
