---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld-2
spec:
  selector:
    matchLabels:
      app: helloworld-2
  # tells deployment to run 2 pods matching the template
  replicas: 2
  # create pods using pod definition in this template
  template:
    metadata:
      labels:
        app: helloworld-2
        env: dev
        author: rolindroy
        application_type: web
        release-version: v1.2
    spec:
      containers:
      - name: helloworld-2
        image: rolindroy/helloworld:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-2
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld-2
